# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a5379cf7638e9d3ecdf94e8bf3fcbd15529ef2f30989f24a466e9f6a9d05a4d7ffd3f62f33f16259029957a2b307523ed11b1ea09f2e692a1c04a6fe9f3058f

test:
  secret_key_base: 5942443263627fb0391e28f7ddbc224d552060f365a7e4b1037529e513d301e455ad21a87c3ef88116aa64048a2097fb218b6b915d14a51c61203c8127e3c134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
